import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { BsApple, BsEye, BsEyeSlash } from "react-icons/bs";
import { FcGoogle } from "react-icons/fc";
/* eslint-disable @next/next/no-img-element */
export default function Authentication() {
  const [showPassword, setShowPassword] = useState(false);
  const handleClickShowPassword = () => {
    setShowPassword(!showPassword);
  };

  return (
    <>
      <Head>
        <title>Authentication Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="authentication">
        <Link href="/" className="auth-logo">
          <img src="/images/benaya-banner-2.png" alt="" />
        </Link>
        <div className="login-form">
          <h1>Create an account</h1>
          <div className="signup-option">
            <BsApple />
            Continue with Apple
          </div>
          <div className="signup-option">
            <FcGoogle />
            Continue with Google
          </div>
          <div className="or">
            <div>or</div>
          </div>
          <form action="">
            <div className="form-card">
              <div className="text-input">
                <input
                  type="text"
                  className="info-input"
                  placeholder="Enter First Name"
                />
              </div>
              <div className="text-input">
                <input
                  type="text"
                  className="info-input"
                  placeholder="Enter Last Name"
                />
              </div>
            </div>
            <div className="email-input">
              <input type="email" placeholder="Enter email address" />
            </div>
            <div className="password-input">
              <input
                type={showPassword ? "text" : "password"}
                placeholder="Enter password"
              />
              {showPassword ? (
                <BsEye
                  className="password-icon"
                  onClick={handleClickShowPassword}
                />
              ) : (
                <BsEyeSlash
                  className="password-icon"
                  onClick={handleClickShowPassword}
                />
              )}
            </div>
            <div className="checkbox-input">
              <input type="checkbox" />
              <span>Yes, I agree to the Terms and Conditions</span>
            </div>
            <button>Create Account</button>
          </form>
          <div className="login-portal">
            Already have an account? <a href="">Login</a>
          </div>
        </div>
        <div className="login-image">
          <img
            src="/images/products/login-image.jpg"
            alt=""
            className="image-up"
          />
          <img
            src="/images/products/login-image-2.jpg"
            alt=""
            className="image-down"
          />
        </div>
      </div>
    </>
  );
}
