import Card from "@/components/Card";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Shop() {
  return (
    <>
      <Head>
        <title>Offical E-commerce Fashion Store by Beverly Naya </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="shop">
        <Card />
        <button>Load More</button>
      </div>
    </>
  );
}
