import Card from "@/components/Card";
import Navbar from "@/components/Navbar";
import Spinner from "@/components/Spinner";
import Head from "next/head";
import { useState } from "react";
import {
  MdOutlineKeyboardArrowDown,
  MdOutlineKeyboardArrowUp,
} from "react-icons/md";

export default function Shop() {
  const [isOpen, setIsOpen] = useState(false);
  const [select, setSelect] = useState([
    "Low To High",
    "$0 - $55",
    "$55 - $100",
  ]);
  const [dropdown, setDropdown] = useState(false);

  const handleDropdown = () => {
    setDropdown(!dropdown);
  };

  const handleSelect = () => {};

  const handleToggle = () => {
    setIsOpen(!isOpen);
  };

  return (
    <>
      <Head>
        <title>
          Product | Offical E-commerce Fashion Store by Beverly Naya{" "}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="shop">
        <div className="sort-range">
          <div className="range-number">Showing 1–12 of 126 results</div>
          <div className="range-price" onClick={handleToggle}>
            Sort by Price:{" "}
            <span className="sort-span" onClick={handleDropdown}>
              <div>{select[2]}</div>
              {dropdown ? (
                <MdOutlineKeyboardArrowDown className="dropdown-icon" />
              ) : (
                <MdOutlineKeyboardArrowUp className="dropdown-icon" />
              )}
              {dropdown && (
                <div className="price-list" onClick={handleSelect}>
                  {select.map((option, index) => {
                    return <div key={index}>{option}</div>;
                  })}
                </div>
              )}
            </span>
          </div>
        </div>
        <Card />
        <button>Load More</button>
        <Spinner />
      </div>
    </>
  );
}
