import Head from "next/head";
import { useEffect, useState } from "react";
import Banner from "./Banner";
import Footer from "./Footer";
import LoadingPage from "./LoadingPage";
import Navbar from "./Navbar";

type LayoutProps = {
  children: React.ReactNode;
};

export default function Layout({ children }: LayoutProps) {
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    // Some async operation that sets isLoading to false
    setTimeout(() => {
      setIsLoading(false);
    }, 3000);
  }, []);

  return (
    <div>
      <Head>
        {/* <title>Offical E-commerce Fashion Store by Beverly Naya </title> */}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <LoadingPage />
      ) : (
        <>
          <Banner />
          <Navbar />
          <main>{children}</main>
          <Footer />
        </>
      )}
    </div>
  );
}
